name: Get and Store AFRR Bid Ladder

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  get_afrr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync
          
      - name: Run fetcher
        env:
          TENNET_API_KEY: ${{ secrets.TENNET_API_KEY }}
        run: python affr_data_fetcher.py
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AFRR data $(date '+%Y-%m-%d %H:%M:%S')" && git push)